// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxcpbpoltxitcwirmbrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4Y3BicG9sdHhpdGN3aXJtYnJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NTk3ODgsImV4cCI6MjA2NjEzNTc4OH0.uMZkQ3VkWHF6IPw8bwTe50RCdmnzr95dLfoxnVq9-vM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);